version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: findo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: findo_db
      MYSQL_USER: findo
      MYSQL_PASSWORD: findopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./user_records_string.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - findo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Findo API Application
  findo-api:
    build: .
    container_name: findo-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Database Configuration
      DATABASE_URL: jdbc:mysql://mysql:3306/findo_db
      DB_USERNAME: findo
      DB_PASSWORD: findopassword

      # JWT Configuration
      JWT_SECRET: myVerySecretKeyForProductionThatShouldBe256BitsLongForSecurityPurposes

      # Upload Directory
      UPLOAD_DIR: /app/uploads

      # CORS Configuration
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001

      # Mail Configuration (configure with your SMTP)
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your-email@gmail.com
      MAIL_PASSWORD: your-app-password

    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - findo-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local

networks:
  findo-network:
    driver: bridge
