server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: findo-api

  datasource:
    # H2 Database (for development)
    url: jdbc:h2:mem:findo_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

    # MySQL Database (for production - uncomment and comment H2 section above)
    # url: jdbc:mysql://localhost:3306/findo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # username: ${DB_USERNAME:root}
    # password: ${DB_PASSWORD:password}
    # driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400 # 24 hours in seconds

# File Upload Configuration
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10485760 # 10MB

# SMS Configuration (Twilio or other provider)
sms:
  provider: ${SMS_PROVIDER:twilio}
  account-sid: ${SMS_ACCOUNT_SID:}
  auth-token: ${SMS_AUTH_TOKEN:}
  from-number: ${SMS_FROM_NUMBER:}

# App Configuration
app:
  max-ads-per-user: 50
  max-photos-per-ad: 10
  admin-emails: ${ADMIN_EMAILS:admin@findo.com}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false

logging:
  level:
    com.findo: DEBUG
    org.springframework.security: DEBUG
